services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx

  redis:
    image: redis/redis-stack
    container_name: redis-server
    restart: unless-stopped
    volumes:
      - redis_data:/data
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - nginx

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - nginx

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    expose:
      - 3000
    networks:
      - nginx
    depends_on:
      - redis
      - postgres

volumes:
  redis_data:
  postgres_data:


networks:
  nginx:
